language: node_js
node_js:
  - '6.9.5'
notifications:
  slack:
    secure: HJ23ChbSZlm2VMUIYOZRZPx0Gaf1/SCz3B7KmfWVF1fPI8IhpQ2hOVeVKbzbcyXpQ0GzJORuSDzxp7qyApQEEaZrGk/A4TSrvtaNDOzAJEP2O7HLQK1MI464bn33UEMJP8dcOHsTI4I5j9ziEz1K7NC80AHq0CVKNHpyrc2VT4aPXFZ6/HBSzfXtGTWEXvnu2G21A9NrK2fQFwX604v4N60TelakcGck3mP9ztG4fbNaqFtSWjIVPvM21vQ07mkUrRF5stG/Hq6QPyvvyLf8Rx0ve9O8yBvzTmKBFCOXUJJnUa00bNyassxxOTebdt2B8wbJZ7hco7EAXOfs5DaBb/qqlqn+FsiLJVKimlZs1j5F5BbUec5+0+9RbM47UXR6gDD56cEVzQgLUHr+xDyoLP//elZvpP4+SAySC0t+3K6bTCZWYRTXQ5BGkdWDwXjtTKElwz6S0UKW5kq2VhYbRSYL05h8ZjlQFNuQJG8KRFAa90VmzG1d4jcDEpOUKPKHR1ym1tFMnAvzCgpuvoXro9WSVWFJ7gOjMvSMM+2Fi/MWLvolMxaBaxgkuBY8ObbzlcPsgFJDqTv3CJvxMiFB9rObtkkUSmF4+YTYe4tW41EmumKMnaLv/wyM9gr0KjUettS2R9Q1kTPROUyrlyEBTmDtN3oVTSOgWRaTUT+x88I=
